# Generated by Django 5.0 on 2026-02-01 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_eggs_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop_expenses',
            options={'verbose_name': '种植费用', 'verbose_name_plural': '种植费用'},
        ),
        migrations.AlterModelOptions(
            name='crop_operations',
            options={'verbose_name': '种植操作', 'verbose_name_plural': '种植操作'},
        ),
        migrations.AlterModelOptions(
            name='crop_sales',
            options={'verbose_name': '采摘批次管理', 'verbose_name_plural': '采摘批次管理'},
        ),
        migrations.AlterModelOptions(
            name='crops',
            options={'verbose_name': '香梨种植地块', 'verbose_name_plural': '香梨种植地块'},
        ),
        migrations.AlterModelOptions(
            name='eggs_production',
            options={'verbose_name': '禽蛋记录', 'verbose_name_plural': '禽蛋记录'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AlterModelOptions(
            name='livestock',
            options={'verbose_name': '物流追踪记录', 'verbose_name_plural': '物流追踪记录'},
        ),
        migrations.AlterModelOptions(
            name='livestock_production',
            options={'verbose_name': '物流生产记录', 'verbose_name_plural': '物流生产记录'},
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name': '机械设备', 'verbose_name_plural': '机械设备'},
        ),
        migrations.AlterModelOptions(
            name='milk_production',
            options={'verbose_name': '产量记录', 'verbose_name_plural': '产量记录'},
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用金额'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Expense_date',
            field=models.DateField(help_text='m/d/y', verbose_name='费用日期'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Expense_description',
            field=models.TextField(verbose_name='费用描述'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Expense_type',
            field=models.CharField(max_length=20, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Payment_method',
            field=models.CharField(max_length=10, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Receipt_number',
            field=models.CharField(max_length=20, verbose_name='收据编号'),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Supplier',
            field=models.CharField(max_length=20, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='crop_operations',
            name='Additional_notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='crop_operations',
            name='Operation_date',
            field=models.DateField(help_text='m/d/y', verbose_name='操作日期'),
        ),
        migrations.AlterField(
            model_name='crop_operations',
            name='Operation_name',
            field=models.CharField(max_length=20, verbose_name='操作名称'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Additional_notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Buyer_information',
            field=models.TextField(verbose_name='买家信息'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Invoice_number',
            field=models.CharField(max_length=20, verbose_name='发票编号'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Payment_method',
            field=models.CharField(max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Payment_status',
            field=models.CharField(choices=[('pending', '待支付'), ('received', '已支付')], max_length=20, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Quantity_sold',
            field=models.CharField(max_length=20, verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Sale_date',
            field=models.DateField(help_text='m/d/y', verbose_name='销售日期'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='crop_sales',
            name='Unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Cid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='地块ID'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Crop_name',
            field=models.CharField(max_length=50, verbose_name='品种'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Field_description',
            field=models.TextField(verbose_name='地块描述'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Field_name',
            field=models.CharField(max_length=50, verbose_name='地块名称'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Harvesting_date',
            field=models.DateField(blank=True, null=True, verbose_name='采摘日期'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Is_harvested',
            field=models.BooleanField(default=False, verbose_name='是否已采摘'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Planting_date',
            field=models.DateField(verbose_name='种植日期'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='Variety',
            field=models.CharField(max_length=20, verbose_name='品种类型'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Comments',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Evening_egg_collection',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='total number of eggs collected', max_digits=10, verbose_name='晚上收集'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Evening_feeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='feed consumed in kg', max_digits=10, verbose_name='晚上饲料'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Midday_egg_collection',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='total number of eggs collected', max_digits=10, verbose_name='中午收集'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Morning_egg_collection',
            field=models.DecimalField(decimal_places=2, help_text='total number of eggs collected', max_digits=10, verbose_name='早晨收集'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Morning_feeds',
            field=models.DecimalField(decimal_places=2, help_text='feed consumed in kg', max_digits=10, verbose_name='早晨饲料'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Poultry_number',
            field=models.IntegerField(verbose_name='家禽数量'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Total_egg_collection',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='总收集'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Total_feeds',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='总饲料'),
        ),
        migrations.AlterField(
            model_name='eggs_production',
            name='Year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Country_code',
            field=models.CharField(max_length=4, verbose_name='国家代码'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Eid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Performance',
            field=models.CharField(max_length=10, verbose_name='绩效'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Phone_number',
            field=models.CharField(max_length=9, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Position',
            field=models.CharField(max_length=10, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Salary',
            field=models.IntegerField(verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='Age',
            field=models.IntegerField(verbose_name='存储时长(天)'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='Animal_type',
            field=models.CharField(max_length=20, verbose_name='物流类型'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='Breed',
            field=models.CharField(max_length=20, verbose_name='产品规格'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='Tag_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='追踪编号'),
        ),
        migrations.AlterField(
            model_name='livestock_production',
            name='Comments',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='livestock_production',
            name='Feed_consumed',
            field=models.DecimalField(decimal_places=2, help_text='field consumed in kg', max_digits=10, verbose_name='饲料消耗'),
        ),
        migrations.AlterField(
            model_name='livestock_production',
            name='Production_amount',
            field=models.CharField(max_length=20, verbose_name='生产数量'),
        ),
        migrations.AlterField(
            model_name='livestock_production',
            name='Production_date',
            field=models.DateField(help_text='m/d/y', verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='Equipment_name',
            field=models.CharField(max_length=20, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='Number_plate',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='Operation',
            field=models.TextField(blank=True, verbose_name='操作说明'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='Purchase_date',
            field=models.DateField(verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='Purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='购买价格'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Evening_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='feed consumed in kg', max_digits=10, verbose_name='晚上消耗'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Evening_production',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='production in litres', max_digits=10, verbose_name='晚上产量'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Livestock_number',
            field=models.IntegerField(verbose_name='牲畜数量'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Midday_production',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='production in litres', max_digits=10, verbose_name='中午产量'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Morning_consumption',
            field=models.DecimalField(decimal_places=2, help_text='feed consumed in kg', max_digits=10, verbose_name='早晨消耗'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Morning_production',
            field=models.DecimalField(decimal_places=2, help_text='production in litres', max_digits=10, verbose_name='早晨产量'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Total_consumption',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='总消耗'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Total_production',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='总产量'),
        ),
        migrations.AlterField(
            model_name='milk_production',
            name='Year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='年份'),
        ),
    ]
