# Generated by Django 5.0 on 2026-02-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_crop_expenses_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='二维码序列号')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='二维码图片')),
                ('qr_content', models.TextField(verbose_name='二维码内容')),
                ('status', models.CharField(choices=[('generated', '已生成'), ('printed', '已打印'), ('attached', '已贴标'), ('scanned', '已扫描')], default='generated', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_scanned', models.DateTimeField(blank=True, null=True, verbose_name='最后扫描时间')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.livestock', verbose_name='关联采摘批次')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '二维码批次管理',
                'verbose_name_plural': '二维码批次管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('scanner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='扫描IP')),
                ('scanner_location', models.CharField(blank=True, max_length=100, verbose_name='扫描地点')),
                ('scan_type', models.CharField(choices=[('production', '生产环节'), ('storage', '仓储环节'), ('logistics', '物流环节'), ('retail', '零售环节'), ('consumer', '消费者查询')], max_length=20, verbose_name='扫描类型')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.qrcodebatch', verbose_name='二维码')),
            ],
            options={
                'verbose_name': '二维码扫描日志',
                'verbose_name_plural': '二维码扫描日志',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
