# Generated by Django 5.0 on 2026-02-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_qrcodebatch_qrcodescanlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('picked', '已采摘'), ('sorted', '已分拣'), ('packaged', '已包装'), ('stored', '已入库'), ('inspected', '已质检'), ('shipped', '已发货'), ('delivered', '已送达'), ('sold', '已销售')], max_length=20, verbose_name='物流状态')),
                ('location', models.CharField(max_length=100, verbose_name='当前位置')),
                ('location_type', models.CharField(choices=[('farm', '果园'), ('packing_house', '包装厂'), ('cold_storage', '冷库'), ('distribution_center', '配送中心'), ('retail_store', '零售店'), ('customer', '消费者')], max_length=20, verbose_name='位置类型')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(℃)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度(%)')),
                ('operation_notes', models.TextField(blank=True, verbose_name='操作备注')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('expected_next_time', models.DateTimeField(blank=True, null=True, verbose_name='预计下一环节时间')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.livestock', verbose_name='关联采摘批次')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '物流追踪记录',
                'verbose_name_plural': '物流追踪记录',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('storage_type', models.CharField(choices=[('cold_storage', '冷库'), ('normal_storage', '普通仓库'), ('packing_area', '包装区'), ('temporary', '临时存放区')], max_length=20, verbose_name='仓库类型')),
                ('capacity', models.FloatField(verbose_name='容量(吨)')),
                ('current_usage', models.FloatField(default=0, verbose_name='当前使用量(吨)')),
                ('address', models.TextField(verbose_name='仓库地址')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('optimal_temperature', models.FloatField(blank=True, null=True, verbose_name='最佳温度(℃)')),
                ('optimal_humidity', models.FloatField(blank=True, null=True, verbose_name='最佳湿度(%)')),
                ('manager_name', models.CharField(max_length=50, verbose_name='仓库管理员')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '仓储管理',
                'verbose_name_plural': '仓储管理',
                'ordering': ['storage_name'],
            },
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stored', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('date_removed', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('storage_duration', models.IntegerField(blank=True, null=True, verbose_name='存储时长(小时)')),
                ('quantity', models.FloatField(verbose_name='数量(公斤)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元/公斤)')),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='总价值(元)')),
                ('quality_grade', models.CharField(choices=[('premium', '特级'), ('grade_a', '一级'), ('grade_b', '二级'), ('grade_c', '三级')], max_length=10, verbose_name='质量等级')),
                ('storage_temperature', models.FloatField(blank=True, null=True, verbose_name='存储温度(℃)')),
                ('storage_humidity', models.FloatField(blank=True, null=True, verbose_name='存储湿度(%)')),
                ('is_in_storage', models.BooleanField(default=True, verbose_name='是否在库')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.livestock', verbose_name='关联采摘批次')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.storage', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '仓储物品',
                'verbose_name_plural': '仓储物品',
                'ordering': ['-date_stored'],
            },
        ),
    ]
